name = "BiodiversityNonuse"
uuid = "8a387b2e-8b11-4a8a-9df0-021ec318e31d"
authors = ["GIVE biodiversity extension contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-b889e2c7f00d"

[targets]
test = ["Test"]
