#!/usr/bin/env python3
"""Transport the published maize response to validated GFDL grid contrasts.

The estimand is an area-weighted log-yield contrast between SSP585 and SSP126
for 2092--2100. This is a published-coefficient transport benchmark, not a new
causal estimate, monetary damage estimate, or SCC result.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

from src.hultgren_maize_response import PublishedEstimate

ROOT = Path(__file__).resolve().parents[1]
KEYS = ["native_lat_index", "native_lon_index"]
WEATHER = [
    "gdd", "kdd",
    "prcp_poly_1_bin1", "prcp_poly_1_bin2", "prcp_poly_1_bin3",
    "prcp_poly_2_bin1", "prcp_poly_2_bin2", "prcp_poly_2_bin3",
]
PRECIP_LINEAR = ["prcp_poly_1_bin1", "prcp_poly_1_bin2", "prcp_poly_1_bin3"]
PRECIP_SQUARED = ["prcp_poly_2_bin1", "prcp_poly_2_bin2", "prcp_poly_2_bin3"]
MODERATORS = ["ln_gdppc", "irrigated_share", "lr_tmax_crop", "lr_prcp_crop"]
COMPONENTS = [
    "joint_climate", "precipitation_all_income_support", "temperature_all_income_support",
    "precipitation_common_positive_support", "precipitation_quantity_reference_scaling",
    "precipitation_distribution_residual",
]
ADAPTATION = {
    "fixed": {"annual_attenuation_rate": 0.0, "cap": 0.0},
    "trend": {"annual_attenuation_rate": 0.003, "cap": 0.35},
    "upper": {"annual_attenuation_rate": 0.007, "cap": 0.70},
}


def digest(path: Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            value.update(block)
    return value.hexdigest()


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def adaptation_factor(year: int, scenario: str, base_year: int = 2020) -> float:
    specification = ADAPTATION[scenario]
    attenuation = min(specification["annual_attenuation_rate"] * max(year - base_year, 0), specification["cap"])
    return 1.0 - attenuation


def design_matrix(frame: pd.DataFrame, terms: list[str]) -> np.ndarray:
    primitives: dict[str, np.ndarray] = {
        column: frame[column].to_numpy(dtype=np.float64) for column in WEATHER + MODERATORS
    }
    primitives["pbarcut_gdd"] = np.minimum(primitives["lr_prcp_crop"], 200.0)
    primitives["pbarcut_kdd"] = np.minimum(primitives["lr_prcp_crop"], 100.0)
    primitives["pbarcut_prcp"] = np.minimum(primitives["lr_prcp_crop"], 250.0)
    primitives["_cons"] = np.ones(len(frame), dtype=np.float64)
    matrix = np.empty((len(frame), len(terms)), dtype=np.float64)
    for index, term in enumerate(terms):
        values = np.ones(len(frame), dtype=np.float64)
        for factor in term.split("#"):
            name = factor.removeprefix("c.")
            require(name in primitives, f"unsupported term factor {name}")
            values *= primitives[name]
        matrix[:, index] = values
    require(np.isfinite(matrix).all(), "nonfinite design matrix")
    return matrix


@dataclass
class ContrastAccumulator:
    terms: int
    weight: float = 0.0
    rows: int = 0
    weighted_design: np.ndarray = field(init=False)
    weighted_log: float = 0.0
    weighted_exact_percent: float = 0.0
    minimum_cell_log: float = math.inf
    maximum_cell_log: float = -math.inf

    def __post_init__(self) -> None:
        self.weighted_design = np.zeros(self.terms, dtype=np.float64)

    def update(self, delta_design: np.ndarray, weights: np.ndarray, estimate: PublishedEstimate, factor: float) -> None:
        require(len(delta_design) == len(weights) and len(weights) > 0, "empty or inconsistent contrast")
        require(np.isfinite(delta_design).all() and np.isfinite(weights).all() and np.all(weights > 0), "invalid contrast inputs")
        scaled = delta_design * factor
        # Elementwise summation avoids platform BLAS warnings generated by the
        # very large interaction-basis values even when the final contrast is finite.
        cell_log = np.sum(scaled * estimate.coefficients[None, :], axis=1, dtype=np.float64)
        cell_exact = 100.0 * np.expm1(cell_log)
        require(np.isfinite(cell_log).all() and np.isfinite(cell_exact).all(), "nonfinite yield response")
        self.weight += float(weights.sum())
        self.rows += len(weights)
        self.weighted_design += np.sum(scaled * weights[:, None], axis=0)
        self.weighted_log += float(np.sum(cell_log * weights, dtype=np.float64))
        self.weighted_exact_percent += float(np.sum(cell_exact * weights, dtype=np.float64))
        self.minimum_cell_log = min(self.minimum_cell_log, float(cell_log.min()))
        self.maximum_cell_log = max(self.maximum_cell_log, float(cell_log.max()))

    def summary(self, estimate: PublishedEstimate) -> dict[str, float | int]:
        require(self.weight > 0, "empty accumulator")
        mean_design = self.weighted_design / self.weight
        mean_log = self.weighted_log / self.weight
        algebra_log = float(np.sum(mean_design * estimate.coefficients, dtype=np.float64))
        require(abs(mean_log - algebra_log) <= 1e-10, "weighted log/design algebra differs")
        variance = float(np.sum(np.multiply.outer(mean_design, mean_design) * estimate.covariance, dtype=np.float64))
        require(variance >= -1e-10, f"negative contrast variance {variance}")
        standard_error = math.sqrt(max(variance, 0.0))
        return {
            "area_or_area_year_weight_ha": self.weight,
            "cell_or_cell_year_rows": self.rows,
            "area_weighted_mean_delta_log_yield": mean_log,
            "percent_change_from_mean_log": 100.0 * math.expm1(mean_log),
            "area_weighted_mean_cell_exact_percent_change": self.weighted_exact_percent / self.weight,
            "coefficient_only_standard_error_log_points": standard_error,
            "coefficient_only_normal_95ci_log_points": [mean_log - 1.96 * standard_error, mean_log + 1.96 * standard_error],
            "coefficient_only_normal_95ci_percent_from_mean_log": [
                100.0 * math.expm1(mean_log - 1.96 * standard_error),
                100.0 * math.expm1(mean_log + 1.96 * standard_error),
            ],
            "minimum_cell_delta_log_yield": self.minimum_cell_log,
            "maximum_cell_delta_log_yield": self.maximum_cell_log,
        }


def weather_year(path: Path, year: int) -> pd.DataFrame:
    columns = ["harvest_year", *KEYS, "mirca_area_ha", "complete", *WEATHER]
    frame = pq.read_table(path, columns=columns, filters=[("harvest_year", "=", year)], use_threads=False).to_pandas()
    require(len(frame) > 0 and frame.harvest_year.eq(year).all(), f"missing year {year}: {path}")
    require(frame.complete.all() and np.isfinite(frame[["mirca_area_ha", *WEATHER]].to_numpy()).all(), "incomplete weather")
    require(len(frame) == len(frame.drop_duplicates(KEYS)), "duplicate weather cell")
    return frame.drop(columns=["harvest_year", "complete"])


def combine_regime_weather(rainfed: pd.DataFrame, irrigated: pd.DataFrame) -> pd.DataFrame:
    frame = rainfed.merge(irrigated, on=KEYS, how="outer", suffixes=("_rainfed", "_irrigated"), validate="one_to_one")
    for regime in ("rainfed", "irrigated"):
        frame[f"mirca_area_ha_{regime}"] = frame[f"mirca_area_ha_{regime}"].fillna(0.0)
    frame["mirca_area_ha"] = frame.mirca_area_ha_rainfed + frame.mirca_area_ha_irrigated
    require(frame.mirca_area_ha.gt(0).all(), "zero combined weather area")
    for feature in WEATHER:
        frame[feature] = (
            frame[f"{feature}_rainfed"].fillna(0.0) * frame.mirca_area_ha_rainfed
            + frame[f"{feature}_irrigated"].fillna(0.0) * frame.mirca_area_ha_irrigated
        ) / frame.mirca_area_ha
    return frame[KEYS + ["mirca_area_ha", *WEATHER]].sort_values(KEYS).reset_index(drop=True)


def validated_weather(path: Path, validation_paths: list[Path]) -> dict:
    build_path = path.with_suffix(path.suffix + ".result.json")
    build = json.loads(build_path.read_text(encoding="utf-8"))
    require(build["status"] == "complete_alternative_product_grid_basis_not_administrative_response_damage_or_scc", "weather build failed")
    file_hash = digest(path)
    require(file_hash == build["output"]["sha256"], "weather build hash differs")
    matches = []
    for validation_path in validation_paths:
        validation = json.loads(validation_path.read_text(encoding="utf-8"))
        if validation.get("basis", {}).get("sha256") == file_hash:
            matches.append((validation_path, validation))
    require(len(matches) == 1, f"weather needs exactly one independent validation: {path}")
    validation_path, validation = matches[0]
    require(validation["status"] == "validated_grid_basis_not_response_damage_or_scc", "weather validation failed")
    return {
        "path": str(path), "sha256": file_hash,
        "build_receipt": str(build_path), "build_receipt_sha256": digest(build_path),
        "validation": str(validation_path), "validation_sha256": digest(validation_path),
    }


def update_support_audit(
    audit: dict, label: str, frame: pd.DataFrame, weights: np.ndarray, support: dict[str, dict[str, float]], columns: list[str]
) -> None:
    target = audit.setdefault(label, {})
    for column in columns:
        record = target.setdefault(column, {"weight": 0.0, "inside_minmax_weight": 0.0, "inside_p01_p99_weight": 0.0})
        values = frame[column].to_numpy(dtype=np.float64)
        bounds = support[column]
        record["weight"] += float(weights.sum())
        record["inside_minmax_weight"] += float(weights[(values >= bounds["minimum"]) & (values <= bounds["maximum"])].sum())
        record["inside_p01_p99_weight"] += float(weights[(values >= bounds["p01"]) & (values <= bounds["p99"])].sum())


def finalize_support_audit(audit: dict) -> dict:
    result = {}
    for label, columns in audit.items():
        result[label] = {}
        for column, record in columns.items():
            result[label][column] = {
                "area_year_fraction_inside_author_minmax": record["inside_minmax_weight"] / record["weight"],
                "area_year_fraction_inside_author_p01_p99": record["inside_p01_p99_weight"] / record["weight"],
            }
    return result


def quantity_counterfactual(reference: pd.DataFrame, comparison: pd.DataFrame) -> tuple[pd.DataFrame, np.ndarray]:
    reference_total = reference[PRECIP_LINEAR].sum(axis=1).to_numpy(dtype=np.float64)
    comparison_total = comparison[PRECIP_LINEAR].sum(axis=1).to_numpy(dtype=np.float64)
    common = (reference_total > 0.0) & (comparison_total > 0.0)
    ratio = comparison_total[common] / reference_total[common]
    result = reference.loc[common].copy()
    for feature in PRECIP_LINEAR:
        result[feature] = result[feature].to_numpy(dtype=np.float64) * ratio
    for feature in PRECIP_SQUARED:
        result[feature] = result[feature].to_numpy(dtype=np.float64) * ratio**2
    return result, common


def decomposition_errors(total: np.ndarray, first: np.ndarray, second: np.ndarray, coefficients: np.ndarray) -> dict[str, float]:
    residual = total - first - second
    maximum_absolute = float(np.max(np.abs(residual)))
    scale = max(1.0, float(np.max(np.abs(total))), float(np.max(np.abs(first))), float(np.max(np.abs(second))))
    response_residual = np.sum(residual * coefficients[None, :], axis=1, dtype=np.float64)
    return {
        "maximum_absolute_design_error": maximum_absolute,
        "maximum_relative_design_error": maximum_absolute / scale,
        "maximum_absolute_log_response_error": float(np.max(np.abs(response_residual))),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference-rainfed", type=Path, required=True)
    parser.add_argument("--reference-irrigated", type=Path, required=True)
    parser.add_argument("--comparison-rainfed", type=Path, required=True)
    parser.add_argument("--comparison-irrigated", type=Path, required=True)
    parser.add_argument("--validation", action="append", type=Path, required=True)
    parser.add_argument("--moderators", type=Path, required=True)
    parser.add_argument("--moderator-receipt", type=Path, required=True)
    parser.add_argument("--author-support", type=Path, required=True)
    parser.add_argument("--coefficients", type=Path, required=True)
    parser.add_argument("--covariance", type=Path, required=True)
    parser.add_argument("--moderator-support", choices=("full", "author_minmax", "author_p01_p99"), default="full")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    require(not args.output.exists(), "fresh output required")

    weather_paths = [args.reference_rainfed, args.reference_irrigated, args.comparison_rainfed, args.comparison_irrigated]
    weather_sources = [validated_weather(path, args.validation) for path in weather_paths]
    moderator_receipt = json.loads(args.moderator_receipt.read_text(encoding="utf-8"))
    require(moderator_receipt["status"] == "alternative_country_income_and_climate_moderators_not_author_replication", "moderator receipt failed")
    require(digest(args.moderators) == moderator_receipt["output"]["sha256"], "moderator hash differs")
    moderators = pd.read_parquet(args.moderators)
    require(len(moderators) == len(moderators.drop_duplicates(KEYS)), "duplicate moderator cell")
    total_area = float(moderators.mirca_area_ha.sum())
    moderators = moderators.loc[moderators.income_available].copy()
    income_matched_area = float(moderators.mirca_area_ha.sum())

    estimate = PublishedEstimate.from_exports(args.coefficients, args.covariance)
    author_record = json.loads(args.author_support.read_text(encoding="utf-8"))
    require(author_record["status"] == "published_estimation_sample_support_summarized", "author support summary failed")
    author_support = author_record["quantiles"]
    require(set(author_support) == set(MODERATORS + WEATHER), "author support variables differ")
    if args.moderator_support != "full":
        lower_name, upper_name = ("minimum", "maximum") if args.moderator_support == "author_minmax" else ("p01", "p99")
        selected = np.ones(len(moderators), dtype=bool)
        for moderator in MODERATORS:
            selected &= moderators[moderator].between(
                author_support[moderator][lower_name], author_support[moderator][upper_name], inclusive="both"
            ).to_numpy()
        moderators = moderators.loc[selected].copy()
    analysis_area = float(moderators.mirca_area_ha.sum())
    require(analysis_area > 0, "moderator support selection is empty")
    years_by_source = []
    for path in weather_paths:
        years_by_source.append(sorted(pq.read_table(path, columns=["harvest_year"]).column(0).unique().to_pylist()))
    require(all(years == years_by_source[0] for years in years_by_source), "weather year supports differ")
    years = years_by_source[0]

    pooled = {
        scenario: {component: ContrastAccumulator(len(estimate.terms)) for component in COMPONENTS}
        for scenario in ADAPTATION
    }
    annual = []
    support_audit: dict = {}
    decomposition_audit = {
        "joint": {"maximum_absolute_design_error": 0.0, "maximum_relative_design_error": 0.0, "maximum_absolute_log_response_error": 0.0},
        "precipitation": {"maximum_absolute_design_error": 0.0, "maximum_relative_design_error": 0.0, "maximum_absolute_log_response_error": 0.0},
    }
    for year in years:
        reference_weather = combine_regime_weather(weather_year(args.reference_rainfed, year), weather_year(args.reference_irrigated, year))
        comparison_weather = combine_regime_weather(weather_year(args.comparison_rainfed, year), weather_year(args.comparison_irrigated, year))
        require(reference_weather[KEYS].equals(comparison_weather[KEYS]), "scenario cell support differs")
        reference = reference_weather.merge(moderators, on=KEYS, how="inner", validate="one_to_one", suffixes=("", "_moderator"))
        comparison = comparison_weather.merge(moderators[KEYS], on=KEYS, how="inner", validate="one_to_one")
        require(reference[KEYS].equals(comparison[KEYS]), "matched scenario order differs")
        require(np.allclose(reference.mirca_area_ha, reference.mirca_area_ha_moderator, rtol=0.0, atol=1e-5), "weather/moderator area differs")
        reference["mirca_area_ha"] = reference.mirca_area_ha_moderator
        reference = reference.drop(columns=["mirca_area_ha_moderator"])
        for column in MODERATORS:
            comparison[column] = reference[column].to_numpy()
        weights = reference.mirca_area_ha.to_numpy(dtype=np.float64)
        require(abs(float(weights.sum()) - analysis_area) <= 1e-5 * analysis_area, "analysis area differs by year")

        precipitation_comparison = reference.copy()
        precipitation_comparison[PRECIP_LINEAR + PRECIP_SQUARED] = comparison[PRECIP_LINEAR + PRECIP_SQUARED]
        temperature_comparison = reference.copy()
        temperature_comparison[["gdd", "kdd"]] = comparison[["gdd", "kdd"]]
        quantity, common_positive = quantity_counterfactual(reference, comparison)
        common_weights = weights[common_positive]

        reference_design = design_matrix(reference, estimate.terms)
        comparison_design = design_matrix(comparison, estimate.terms)
        precipitation_design = design_matrix(precipitation_comparison, estimate.terms)
        temperature_design = design_matrix(temperature_comparison, estimate.terms)
        quantity_design = design_matrix(quantity, estimate.terms)
        deltas = {
            "joint_climate": comparison_design - reference_design,
            "precipitation_all_income_support": precipitation_design - reference_design,
            "temperature_all_income_support": temperature_design - reference_design,
            "precipitation_common_positive_support": (precipitation_design - reference_design)[common_positive],
            "precipitation_quantity_reference_scaling": quantity_design - reference_design[common_positive],
            "precipitation_distribution_residual": precipitation_design[common_positive] - quantity_design,
        }
        year_joint_error = decomposition_errors(
            deltas["joint_climate"], deltas["precipitation_all_income_support"],
            deltas["temperature_all_income_support"], estimate.coefficients,
        )
        year_precip_error = decomposition_errors(
            deltas["precipitation_common_positive_support"],
            deltas["precipitation_quantity_reference_scaling"],
            deltas["precipitation_distribution_residual"], estimate.coefficients,
        )
        for label, current in (("joint", year_joint_error), ("precipitation", year_precip_error)):
            for metric, value in current.items():
                decomposition_audit[label][metric] = max(decomposition_audit[label][metric], value)

        update_support_audit(support_audit, "transport_moderators", reference, weights, author_support, MODERATORS)
        update_support_audit(support_audit, "ssp126_weather", reference, weights, author_support, WEATHER)
        update_support_audit(support_audit, "ssp585_weather", comparison, weights, author_support, WEATHER)
        year_record = {
            "harvest_year": year,
            "analysis_area_ha": float(weights.sum()),
            "common_positive_precipitation_area_fraction_of_analysis": float(common_weights.sum() / weights.sum()),
            "adaptation": {},
        }
        for scenario in ADAPTATION:
            factor = adaptation_factor(year, scenario)
            year_record["adaptation"][scenario] = {"remaining_effect_factor": factor, "components": {}}
            for component, delta in deltas.items():
                component_weights = common_weights if component in COMPONENTS[3:] else weights
                current = ContrastAccumulator(len(estimate.terms))
                current.update(delta, component_weights, estimate, factor)
                pooled[scenario][component].update(delta, component_weights, estimate, factor)
                year_record["adaptation"][scenario]["components"][component] = current.summary(estimate)
        annual.append(year_record)

    for label, audit in decomposition_audit.items():
        require(audit["maximum_relative_design_error"] <= 1e-12, f"{label} relative design decomposition failed")
        require(audit["maximum_absolute_log_response_error"] <= 1e-10, f"{label} response decomposition failed")
    pooled_results = {
        scenario: {component: accumulator.summary(estimate) for component, accumulator in components.items()}
        for scenario, components in pooled.items()
    }
    finalized_support = finalize_support_audit(support_audit)
    result = {
        "schema": "hultgren_grid_yield_scenario_transport/v1",
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "status": "preliminary_published_coefficient_transport_not_causal_damage_or_scc",
        "estimand": "fixed-MIRCA-area SSP585 minus SSP126 maize log-yield response, GFDL-ESM4, 2092-2100",
        "years": years,
        "sources": {
            "weather": weather_sources,
            "moderators": {"path": str(args.moderators), "sha256": digest(args.moderators), "receipt": str(args.moderator_receipt), "receipt_sha256": digest(args.moderator_receipt)},
            "author_estimation_sample_support": {
                "path": str(args.author_support), "sha256": digest(args.author_support),
                "source": author_record["source"], "complete_rows": author_record["complete_rows"],
            },
            "coefficients": {"path": str(args.coefficients), "sha256": digest(args.coefficients)},
            "covariance": {"path": str(args.covariance), "sha256": digest(args.covariance)},
        },
        "support": {
            "total_eligible_mirca_area_ha": total_area,
            "income_matched_area_ha": income_matched_area,
            "income_matched_area_fraction": income_matched_area / total_area,
            "moderator_support_selection": args.moderator_support,
            "analysis_area_ha": analysis_area,
            "analysis_area_fraction_of_total": analysis_area / total_area,
            "analysis_area_fraction_of_income_matched": analysis_area / income_matched_area,
            "author_sample_quantiles": author_support,
            "transport_overlap": finalized_support,
        },
        "adaptation_scenarios": {
            name: {**specification, "base_year": 2020, "interpretation": "exogenous attenuation scenario, not an empirical estimate"}
            for name, specification in ADAPTATION.items()
        },
        "annual": annual,
        "pooled_area_year_weighted": pooled_results,
        "decomposition": {
            "numerical_audit": decomposition_audit,
            "quantity_path": "uniformly scale every SSP126 monthly precipitation amount so season total equals SSP585; phase linear terms scale by ratio and monthly-square sums by ratio squared",
            "distribution_definition": "SSP585 precipitation response minus the quantity-only reference-distribution path response on common-positive rainfall support",
            "warning": "quantity/distribution split is reference-path dependent and is not a unique causal decomposition",
        },
        "uncertainty": "reported standard errors propagate the published coefficient covariance only; they exclude climate-model, weather-product, moderator-transport, adaptation, crop-area, and structural uncertainty",
        "interpretation": (
            "preliminary response-function transport using fixed country-level PWT income and alternative 27-year GSWP3-W5E5 climate moderators; "
            "not the authors' subnational/time-varying moderator construction and not yet monetized or run through a marginal emissions pulse"
        ),
        "claim_gates": {
            "validated_physical_weather_inputs": True,
            "published_response_algebra_validated": True,
            "author_moderator_replication": False,
            "new_causal_yield_estimate": False,
            "monetary_damage": False,
            "scc": False,
        },
        "implementation": {"path": str(Path(__file__).resolve().relative_to(ROOT)), "sha256": digest(Path(__file__).resolve())},
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({
        "status": result["status"], "support_selection": args.moderator_support,
        "analysis_area_fraction_of_total": result["support"]["analysis_area_fraction_of_total"],
        "fixed_pooled": pooled_results["fixed"], "decomposition": result["decomposition"],
    }, indent=2))


if __name__ == "__main__":
    main()
